image : etiennec27/laravelphp:latest

stages:         
  - test
  - build
  - deploy

frontend-test:   
  stage: test    
  tags:
    - tag-runner1
  script:
    - echo "Running unit tests... This will take a few seconds."
    - sleep 60
    - echo "Code coverage is 90%"

backend-test:   
  stage: test   
  tags:
    - tag-runner2
  # only:
  #   - main
  script:
    - echo "Running unit tests... This will take a few seconds."
    - cd backend/back
    - cp .env .env.testing
    - ./vendor/bin/phpunit tests/
    - cd ../../


build-backend:       
  stage: build
  tags:
    - tag-runner2
  # only:
  #   - main
  artifacts:
    paths:
      - backend/back/vendor/
      - backend/back/public/css/
      - backend/back/public/js/
      - backend/back/public/modules/
      - backend/back/public/mix-manifest.json
  script:
    - cd backend/back
    - composer update
    - composer install --optimize-autoloader --no-dev
    - php artisan migrate --force
    - php artisan db:seed
    - cd ..

deploy-job:      
  stage: deploy  
  tags:
    - tag-runner1
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."