---
- name: NGINX | Install nginx 
  apt: 
    update_cache: yes
    name: nginx
    state: present
  notify:
    - Start nginx

- name: NGINX | Install nginx 
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Reload nginx

# - name: NGINX | Copy Configuration
#   template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#   notify: restart nginx