---
- name: frontend
  hosts: frontend
  remote_user: root
  tasks:
  - include_vars:
      file: ../vars.yml

  - name: FILE | Create directory
    file:
      path: "{{ frontend_workdir }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775
      recurse: yes

  - name: FILE | Copy frontend project
    copy:
      src: ../../frontend/front/
      dest: "{{ frontend_workdir }}"
      owner: "{{ user }}"
      group: "{{ user }}"

  - include_role:
      name: ../nginx/

  - include_role:
      name: ../nodejs/
