---
- name: Backend
  hosts: backend
  remote_user: root
  tasks:
  - include_vars:
      file: ../vars.yml

  - name: FILE | Create directory
    file:
      path: "{{ backend_workdir }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775
      recurse: yes

  - name: FILE | Copy backend project
    copy:
      src: ../../backend/back/
      dest: "{{ backend_workdir }}"
      owner: "{{ user }}"
      group: "{{ user }}"

  - include_role:
      name: ../php/
