---
- name: All
  hosts: all
  remote_user: root
  tasks:
  - name: "USER | Create user {{ user }}"
    user: 
      name: "{{ user }}"
      shell: /bin/bash

  - name: USER | Ssh key
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: "USER | Sudoers {{ user }}"
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "^{{ user }}"
      line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - include_role:
      name: ../roles/tools/

