---
- name: Start nginx
  service:
    name: nginx
    state: started
  become: true

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  become: true

# - name: restart nginx
#   service: 
#     name: nginx 
#     state: restarted
#     enabled: yes
